POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudHRpIiwiaWQiOiI2MDlkN2RkZGU0YjFlMjZmMTRkZjM0ZTAiLCJpYXQiOjE2MjA5MzQxNDAsImV4cCI6MTYyMDkzNzc0MH0.35dHDVd3dcsdIG7cY1QN3OxwPdhF8HAbjFoUhYHdNls

{
  "title": "tojiiko",
  "author": "tojii ehkä",
  "url": "www.tojikka.com",
  "likes": 100,
  "userId": "609a469199027c3ea8354fa9"
}

//poistotestissä tämä on tekijä